### ISSUE TITLE
Failed to load the filesize package

### ISSUE THREAD

**Issue by JawKnee5150** [mkxml/atom-filesize#20] opened 2017-03-06 21:37 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Ultimate 
**Thrown From**: [filesize](https://github.com/mkxml/atom-filesize) package 2.0.4

### Stack Trace

Failed to load the filesize package

```
At Cannot find module 'filesize-calculator'

Error: Cannot find module 'filesize-calculator'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.14.4/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-filesize/lib/filesize-view.js:4:34)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-filesize/lib/filesize.js:4:55)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at /app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/app.asar/src/package-manager.js:407:19)
```

### Commands

```
     -0:15.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
file-icons 2.0.17 
filesize 2.0.4 
javascript-snippets 1.2.1 
color-picker 2.2.5 
linter 1.99.0 
```

**Comment by mkxml** [comment] 2017-03-09 23:43
Hi @JawKnee5150, thanks for the report. Also, sorry for the delay.

Strange situation, I can't reproduce it yet. I need some more info.

When exactly did it crash? First time using it?

Do you have the status-bar enabled?

**Comment by mkxml** [comment] 2017-05-03 22:19
Closing this for now since it appears to be an isolated problem. I will reopen if needed.

**Closed as completed by mkxml** 2017-05-03 22:19 UTC

**Comment by Shiv-Dangi** [comment] 2018-05-31 07:50
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.3
**Thrown From**: [filesize](https://github.com/mkxml/atom-filesize) package 4.0.1


### Stack Trace

Failed to load the filesize package

```
At cannot enable cancellation after promises are in use

Error: cannot enable cancellation after promises are in use
    at Function.Promise.config (/packages/prettier-atom/node_modules/bluebird/js/release/debuggability.js:272:19)
    at /packages/filesize/node_modules/filesize-calculator/index.js:56:9)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/filesize/lib/filesize.js:3:55)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:887:35)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:144:18)
    at PackageManager.module.exports.PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:565:22)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:495:27)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:643:36)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:519:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -9:33.9.0 atom-beautify:beautify-file (span.name.icon.icon-file-text)
     -6:05.8.0 command-palette:toggle (div.tool-panel.tree-view)
     -5:58.8.0 settings-view:core (div.tool-panel.tree-view)
  6x -5:48.5.0 core:backspace (input.hidden-input)
  3x -5:16.5.0 core:move-left (input.hidden-input)
     -5:15.6.0 core:backspace (input.hidden-input)
     -5:00.3.0 command-palette:toggle (input.hidden-input)
 25x -4:58.5.0 core:move-down (input.hidden-input)
     -4:44 settings-view:install-packages-and-themes (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.6 
busy-signal 1.4.3 
filesize 4.0.1 
intentions 1.1.5 
language-babel 2.85.0 
linter 2.2.0 
linter-ui-default 1.6.8 
node-debugger 1.10.1 
prettier-atom 0.53.0 
ruby-slim 0.2.0 
```
