### ISSUE TITLE
Loading time

### ISSUE THREAD

**Issue by eboracus** [mkxml/atom-filesize#10] opened 2015-11-19 21:34 UTC
I've been noticing recently that `atom-filesize` consistently appears at the very top of the timecop "Package Loading" list. For the relative scope of the package I'm slightly surprised that the overheads seem (relatively) so significant, for me at least. Do others experience this also, is it a known issue?

![filesize_load_time](https://cloud.githubusercontent.com/assets/11758299/11284695/28f3ed7c-8f03-11e5-8dc7-18ee7883e231.png)

I did notice, (I think) after a recent update, that the `atom-filesize` contribution to the "Package Activation" top list had gone. Is there anything that can be done to lower the loading time in the same direction? :)

**Comment by mkxml** [comment] 2015-11-20 11:13
Hello @eboracus, thanks for the heads up!

I'm noticing that as well since `0.3.0`, I believe it's due to the loading of Node.JS packages we rely on to show more information about the file.

Before 0.2.0 there was no request to external `node` packages so the loading time was faster.

I will take a look on how to improve that, maybe there's some part of the Atom API I'm missing. There must be a way to cache those module dependencies.

**Comment by mkxml** [comment] 2015-11-20 11:42
OK, turns out that Atom loads the external files each time it loads a view. But it only calls the activation method once.

So I changed the `require` statements so that they only include files on package activation.

The load time should be improved in `0.4.2`. Please update filesize and give me feedback.

**Notice:** When testing with Timecop remember that when Atom opens for the first time it compiles the CoffeeScript of all packages.

On my machine Atom takes about 10ms just to compile `filesize` on application cold start.

That does not happen when loading subsequent windows.

Thank you for this finding @eboracus! :sunglasses:

I will wait for your feedback so I can close the issue.

**Comment by eboracus** [comment] 2015-11-30 22:40
Thanks for such a prompt update... apologies for a slower response :(

I see, that makes sense.

Just tested the newer version. I look to be getting similar times (~100-150ms) for activation times now as for load times previously. I've been comparing numbers by starting/restarting multiple times and opening new windows. I still seem to get the same activation time on opening subsequent windows, should that not happen(?) Multiple restarts and/or new windows in each case and the averages are very similar, in the range above.

Is it possible to only activate the majority of the extra modules when the option to display more information is on. Tried turning it off out of curiosity, but still the same activation times.

Edit: Just emphasising this is, of course, pretty minor - just trying to help optimise if worthwhile. Package itself still obviously working great :sunglasses:

**Comment by mkxml** [comment] 2015-12-14 17:50
Hey @eboracus, sorry for the delay on this thread but I've been testing `atom-filesize` for the past couple weeks trying to identify the cause of the problem. I'm almost certain it's the way `node` modules are required in Atom.

The change made in `0.4.2` just passed the problem from package loading to package activation.

The external `node` modules are mainly used to get the tooltip information that shows when the user clicks.

As you suggested we could try loading lazy loading the packages when the user first clicks the `filesize` components.

I'll try an approach this week and keep this thread posted.

Anyways, thank you @eboracus for taking the time to perform the tests :smile:.

**Comment by mkxml** [comment] 2016-10-12 12:56
Hello again @eboracus.

A complete rewrite of the package has been done. It's no longer CoffeeScript code, it's now JS/ES2015.

In my testings I can confirm that the package is a lot faster to load and activate.

That has been accomplished by lazy loading modules and tooltip information as we discussed in the past.

Check the screenshots below for a before/after comparison:

The test was done in a 2012 MacbookPro, no SSD. They represent Atom warm boot (cached scripts) after the machine is started. You can see that we are not comparing CoffeeScript to Babel compilations because it's already cached on both screenshots.

Also I can say that those activation numbers vary a lot depending on the machine situation. Sometimes the newer version of the package starts close to 1ms, sometimes at 10ms. I couldn't get slower times on this machine though.

Nevertheless, you can see it's a lot faster than the previous version.

Version v0.4.2 - CoffeeScript version with no lazy loading
![filesize_activate_v0_4_2](https://cloud.githubusercontent.com/assets/1051644/19310601/4787032c-9061-11e6-9e6b-4415f0bc99ff.jpg)

Version v1.0.0 - ES2015 version with lazy requires and loading of tooltip info only when needed
![filesize_activate_v1_0_0](https://cloud.githubusercontent.com/assets/1051644/19310753/03eb9c12-9062-11e6-8a84-481784bd8254.jpg)

I'm closing this issue for now, if you have any considerations please feel free to ping me.

**Closed as completed by mkxml** 2016-10-12 12:56 UTC

**Comment by eboracus** [comment] 2016-10-13 00:30
Hey,

Really nice rewrite/upgrade. 👍 I've lightly tested on my machine and I see the same massive improvement in activation time with warm starts as you see above (~6-9ms here). So awesome. Hooray for lazy load!

No issues I see here all looks streamlined, so only a note to acknowledge the much appreciated effort. Great work! 🍻 👍
